# Generated by Django 4.0.2 on 2025-05-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0003_alter_movie_file_alter_movie_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Musical', 'Musical'), ('Crime', 'Crime'), ('Family', 'Family'), ('Historical', 'Historical'), ('Western', 'Western'), ('Biography', 'Biography'), ('War', 'War'), ('Indie', 'Indie')], max_length=20),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fullname', models.CharField(max_length=1000)),
                ('age', models.IntegerField()),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('nostalgic', 'Nostalgic'), ('anxious', 'Anxious'), ('excited', 'Excited'), ('romantic', 'Romantic'), ('heartbroken', 'Heartbroken')], max_length=20, null=True)),
                ('sub_genre', models.JSONField(default=list, null=True)),
                ('year', models.IntegerField(null=True)),
                ('director', models.CharField(max_length=300, null=True)),
                ('cast', models.JSONField(default=list, null=True)),
                ('language', models.CharField(max_length=20)),
                ('era', models.CharField(max_length=300, null=True)),
                ('actors', models.JSONField(default=dict, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('preferred_genre', models.ManyToManyField(to='netflix.Category')),
                ('previous_watch', models.ManyToManyField(related_name='previous_for_user', to='netflix.Movie')),
                ('similar_movies', models.ManyToManyField(related_name='similar_for_users', to='netflix.Movie')),
            ],
        ),
    ]
