# Generated by Django 4.0.2 on 2025-05-04 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0004_movie_cast_movie_director_movie_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=20, null=True),
        ),
    ]
