# Generated by Django 4.0.2 on 2025-05-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0005_alter_movie_category_alter_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='preview_image',
            field=models.ImageField(default='preview_images/r2.PNG', upload_to='preview_images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2000, null=True),
        ),
    ]
