# Generated by Django 4.0.2 on 2025-05-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0006_alter_movie_preview_image_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommended_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
