// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrJxLkolNpF8Sic-Eir5m8WYwX6M2igX0',
    appId: '1:507407242653:web:77234d46f63fe1d5070b74',
    messagingSenderId: '507407242653',
    projectId: 'matfixer-ai',
    authDomain: 'matfixer-ai.firebaseapp.com',
    storageBucket: 'matfixer-ai.firebasestorage.app',
    measurementId: 'G-TVGDDZ62C1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfgFc8nuJYDZhUFIo0Akaum7dSCE2NjtY',
    appId: '1:507407242653:ios:9fd4888b0d6c20ac070b74',
    messagingSenderId: '507407242653',
    projectId: 'matfixer-ai',
    storageBucket: 'matfixer-ai.firebasestorage.app',
    iosClientId: '507407242653-qh8g72g1u1ubcmakhbmabbamdfe2r1mg.apps.googleusercontent.com',
    iosBundleId: 'io.github.amansikarwar.matfixer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrJxLkolNpF8Sic-Eir5m8WYwX6M2igX0',
    appId: '1:507407242653:web:2948ddcee66bbf80070b74',
    messagingSenderId: '507407242653',
    projectId: 'matfixer-ai',
    authDomain: 'matfixer-ai.firebaseapp.com',
    storageBucket: 'matfixer-ai.firebasestorage.app',
    measurementId: 'G-BGXXT9LW9Y',
  );

}